apiVersion: v1
data:
  database-name: c2FtcGxlZGI=
  database-password: RUVVbk9sRWVqdmxydUVWYQ==
  database-user: dXNlclJRMg==
kind: Secret
metadata:
  annotations:
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
  creationTimestamp: "2026-06-12T02:18:06Z"
  labels:
    template: postgresql-persistent-template
    template.openshift.io/template-instance-owner: 8285b1ec-68b8-4bb4-9d3e-f360df5e18c1
  name: postgresql
  namespace: tefadow920-dev
  resourceVersion: "5653693697"
  uid: 35bd3f99-f537-48b8-ad01-97f4784328d6
type: Opaque
