apiVersion: v1
data:
  database-password: WE9qWEwyRU1zT0VhdXFZVg==
kind: Secret
metadata:
  annotations:
    template.openshift.io/expose-password: '{.data[''database-password'']}'
  creationTimestamp: "2026-06-12T04:38:09Z"
  labels:
    template: redis-persistent-template
    template.openshift.io/template-instance-owner: a4c66b14-7e34-422a-9ede-008e3031db9f
  name: redis
  namespace: tefadow920-dev
  resourceVersion: "5654143314"
  uid: a7a89cf6-b362-4144-a07b-2ca15172466e
type: Opaque
